### ISSUE TITLE
SVGs

### ISSUE THREAD

**Issue by rickysullivan** [kkulbae/craco-image-optimizer-plugin#1]
Does this work with SVGs?

**Comment by kkulbae** [comment]
I'm sorry for late answer

This project is dependence on [image-webpack-loader](https://github.com/tcoopman/image-webpack-loader).

SVG file are supported by [image-webpack-loader](https://github.com/tcoopman/image-webpack-loader).

it seems to use the imagemin-svgo library to support it

See [image-webpack-loader](https://github.com/tcoopman/image-webpack-loader#options) for exact options

Thank you.
